.class public interface abstract Llecho/lib/hellocharts/formatter/AxisValueFormatter;
.super Ljava/lang/Object;
.source "AxisValueFormatter.java"


# virtual methods
.method public abstract formatValueForAutoGeneratedAxis([CFI)I
.end method

.method public abstract formatValueForManualAxis([CLlecho/lib/hellocharts/model/AxisValue;)I
.end method
