.class public Llecho/lib/hellocharts/model/Axis;
.super Ljava/lang/Object;
.source "Axis.java"


# static fields
.field public static final DEFAULT_MAX_AXIS_LABEL_CHARS:I = 0x3

.field public static final DEFAULT_TEXT_SIZE_SP:I = 0xc


# instance fields
.field private formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

.field private hasLines:Z

.field private hasSeparationLine:Z

.field private hasTiltedLabels:Z

.field private isAutoGenerated:Z

.field private isInside:Z

.field private lineColor:I

.field private maxLabelChars:I

.field private name:Ljava/lang/String;

.field private textColor:I

.field private textSize:I

.field private typeface:Landroid/graphics/Typeface;

.field private values:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Llecho/lib/hellocharts/model/AxisValue;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>()V
    .registers 4

